### ISSUE TITLE
Missing municipality id in 1991 population table

### ISSUE THREAD

**Issue by jvbatista1** [ipeaGIT/censobr#39] opened 2024-01-30 14:03 UTC
Hi @rafapereirabr !

I have used the population and household tables from 2010 to 1980. In 1991 I found a problem in the identification code column of the municipality of the observation. I don't know if I'm doing something wrong, but of the 17,045,653 observations, 8,575,800 are missing from this column. I was surprised when I couldn't filter the information for the municipality of Rio de Janeiro. Here's the code I used to test it:

```
> census1991_2 <- read_population(year = 1991, cache = T)
Reading data cached locally.
> census1991_2 |> 
+   select(code_muni) |> 
+   mutate(test = is.na(code_muni)) |> 
+   count(test) |>
+   collect()
# A tibble: 2 × 2
  test        n
  <lgl>   <int>
1 FALSE 8469853
2 TRUE  8575800
```

**Comment by rafapereirabr** [comment] 2024-01-30 14:51
Hi @jvbatista1 , thank you for opening this issue !

Indeed, I just checked the data it looks like there is an error in the `code_muni` column (reprex below). I will have a closer look at this in the next few weeks.

```
library(censobr)
library(dplyr)

census1991_2 <- censobr::read_population(year = 1991)

df <- census1991_2 |> 
      select(code_muni) |> 
      mutate(code_muni = as.numeric(code_muni)) |>
      collect()

summary(df$code_muni)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
#> 1710508 2930808 3519600 3395935 3550308 5222054 8575800 
```

**Comment by rafapereirabr** [comment] 2024-04-29 01:35
Hi @jvbatista1. Thanks for your patience. I have now fixed the 1991 population and household data sets. To make sure you use the updated version, please delete the old files from your cache with the following code:

### clean 1991 data sets from the cache:
```
library(censobr)
library(dplyr)

censobr::censobr_cache(delete_file = '1991_population')
censobr::censobr_cache(delete_file = '1991_household')

```


### check whether see the issue is now gone:
```
df <- censobr::read_households(year = 1991)

df |> 
 select(code_muni) |> 
 mutate(test = is.na(code_muni)) |> 
 count(test) |>
 collect()


df2 <- censobr::read_population(year = 1991)

df2 |> 
  select(code_muni) |> 
  mutate(test = is.na(code_muni)) |> 
  count(test) |>
  collect()
```

**Closed** 2024-04-29 01:45 UTC
